# Generated by Django 4.2.8 on 2023-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active status'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Ahmed Gamal', max_length=120),
            preserve_default=False,
        ),
    ]
