version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipes_api_proj
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data:
