---
name: CI

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.0.4
    steps:
      - name: Login to hub.docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "python manage.py flake8"
